### ISSUE TITLE
Trying to get the next 2 days overall intensity figures

### ISSUE THREAD

**Issue by dabeeeenster** [BottlecapDave/HomeAssistant-CarbonIntensity#21]
### Describe the bug

I cant figure out how to display these figures in HA taken from https://carbonintensity.org.uk/

<img width="676" alt="image" src="https://github.com/user-attachments/assets/c88d72ce-488e-42c9-aa6d-afc4183acbfb" />

Sorry if I'm being stupid - is there a simple way of retrieving this data?

### Reproduction steps

Install integration, cant find easy way of getting this data

### Expected behaviour

Find an easy way of getting this data

### Integration Version

v3.0.1

### Home Assistant Version

2024.12.1

### Fresh Install?

Fresh install

### Home Assistant Logs

NA

**Comment by BottlecapDave** [comment]
Hello. Sorry for the very late response. As per the website, those values are the average, min and max carbon intensity. There is no indication on what region this is for, so I assume its national.

Todays values can be found in the [current day rates](https://bottlecapdave.github.io/HomeAssistant-CarbonIntensity/entities/#current-day-rates) sensor and tomorrows values can be found in the [next day rates](https://bottlecapdave.github.io/HomeAssistant-CarbonIntensity/entities/#next-day-rates) sensor.

These values can then be calculated like so

```
{{ state_attr('event.carbon_intensity_national_current_day_rates', 'rates') | map(attribute='intensity_forecast') | min }}
{{ state_attr('event.carbon_intensity_national_current_day_rates', 'rates') | map(attribute='intensity_forecast') | max }}
{{ state_attr('event.carbon_intensity_national_current_day_rates', 'rates') | map(attribute='intensity_forecast') | average }}
```

rinse and repeat for the next day.

You can then use this with a [markdown card](https://www.home-assistant.io/dashboards/markdown/), or try something more fancy

```
| Day | Min | Max | Average |
|-|-|-|-|
|Today | {{ state_attr('event.carbon_intensity_national_current_day_rates', 'rates') | map(attribute='intensity_forecast') | min }} | {{ state_attr('event.carbon_intensity_national_current_day_rates', 'rates') | map(attribute='intensity_forecast') | max }} | {{ state_attr('event.carbon_intensity_national_current_day_rates', 'rates') | map(attribute='intensity_forecast') | average }} |
|Tomrrow | {{ state_attr('event.carbon_intensity_national_next_day_rates', 'rates') | map(attribute='intensity_forecast') | min }} | {{ state_attr('event.carbon_intensity_national_next_day_rates', 'rates') | map(attribute='intensity_forecast') | max }} | {{ state_attr('event.carbon_intensity_national_next_day_rates', 'rates') | map(attribute='intensity_forecast') | average }} |
```

There are no plans to go beyond the next day, as this information is not required for the target rate sensors, and this information is only really available as a bi-product of that.

**Comment by dabeeeenster** [comment]
Ah thanks so much for the reply! I couldnt figure that out so I built these sensors which hit the API directly and work too, if anyone is interested:

```yaml
- platform: rest
  name: "Carbon Intensity Today"
  resource_template: https://api.carbonintensity.org.uk/intensity/stats/{{ now().strftime('%Y-%m-%d') }}/{{ (now() + timedelta(day
s = 1)).strftime('%Y-%m-%d') }}
  value_template: "{{ value_json.data[0].intensity.min }}"

- platform: rest
  name: "Carbon Intensity Tomorrow"
  resource_template: https://api.carbonintensity.org.uk/intensity/stats/{{ (now() + timedelta(days = 1)).strftime('%Y-%m-%d') }}/{
{ (now() + timedelta(days = 2)).strftime('%Y-%m-%d') }}
  value_template: "{{ value_json.data[0].intensity.min }}"

- platform: rest
  name: "Carbon Intensity 2 days"
  resource_template: https://api.carbonintensity.org.uk/intensity/stats/{{ (now() + timedelta(days = 2)).strftime('%Y-%m-%d') }}/{
{ (now() + timedelta(days = 3)).strftime('%Y-%m-%d') }}
  value_template: "{{ value_json.data[0].intensity.min }}"

- platform: rest
  name: "Carbon Intensity 3 days"
  resource_template: https://api.carbonintensity.org.uk/intensity/stats/{{ (now() + timedelta(days = 3)).strftime('%Y-%m-%d') }}/{
{ (now() + timedelta(days = 4)).strftime('%Y-%m-%d') }}
  value_template: "{{ value_json.data[0].intensity.min }}"
```
